name = "partime-api"
main = "worker/index.ts"
compatibility_date = "2026-04-18"

[env.staging]
name = "partime-api-staging"

[env.staging.vars]
API_PREFIX = "/api"
ALLOWED_ORIGINS = ""

[[env.staging.d1_databases]]
binding = "DB"
database_name = "partime-db-staging"
database_id = "83e06a84-25ce-4575-89d8-3d0504fa5260"
migrations_dir = "worker/db/migrations"

[env.production]
name = "partime-api-production"

[env.production.vars]
API_PREFIX = "/api"
ALLOWED_ORIGINS = "https://partime-abb.pages.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "partime-db-production"
database_id = "97b686ea-7e8f-4cdc-9719-ed5aad45bb88"
migrations_dir = "worker/db/migrations"
